### ISSUE TITLE
FIX: The futex facility returned an unexpected error code.

### ISSUE THREAD

**Issue by yang-stressfree** [twolfson/katex-screenshot#12]
Install xvfb first, then run cmd like `xvfb-run katex-screenshot vector.tex vector.png`.

https://www.electronjs.org/docs/tutorial/testing-on-headless-ci

**Comment by twolfson** [comment]
Our CI runs headlessly with Xvfb as well. I just re-ran it without any issues =/

https://app.circleci.com/pipelines/github/twolfson/katex-screenshot/45/workflows/a8b7ff13-f5d6-4118-923e-33a3c33eda45

https://github.com/twolfson/katex-screenshot/blob/1.4.1/.circleci/config.yml#L34

https://circleci.com/docs/2.0/circleci-images/#pre-installed-tools

Closing as `wontfix`

**Comment by yang-stressfree** [comment]
Emm, I created this issue to document how to fix 'The futex facility returned an unexpected error code' for someone else who may face the same problem.

**Comment by twolfson** [comment]
Ah, I see. Thank you for documenting it then =)
